# Generated by Django 4.2.6 on 2023-10-31 04:02

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdharCard',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('adharnumber', models.CharField(help_text='000011112222', max_length=12, primary_key=True, serialize=False, unique=True, validators=[polls.models.CustomValidators.adharvalidator])),
                ('phone_number', models.CharField(max_length=10, validators=[polls.models.CustomValidators.phonevalidator])),
                ('dob', models.DateField(validators=[polls.models.CustomValidators.dobvalidtor])),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('level', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('End_date', models.DateField()),
                ('Duration', models.DurationField()),
            ],
        ),
    ]
