# Generated by Django 4.2.6 on 2023-10-31 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='End_date',
            field=models.DateTimeField(),
        ),
    ]
