# Generated by Django 4.2.6 on 2023-10-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_election_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='Duration',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
    ]
