# Generated by Django 4.2.6 on 2023-10-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_election_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='isused',
            field=models.BooleanField(auto_created=True, blank=True, default=False),
        ),
    ]
