#!/bin/bash

if [ $@ == 3 ]
then
    py manage.py createsuperuser 
fi

if [ $@ == 1  ]
then
    py manage.py makemigrations Adminserver
    py manage.py migrate
else
    py manage.py runserver 8888
fi
