# Generated by Django 4.2.6 on 2023-11-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('top_hash', models.CharField(max_length=1024)),
                ('vote', models.CharField(max_length=2048, primary_key=True, serialize=False)),
                ('slat', models.CharField(max_length=500)),
                ('time_stamp', models.DateTimeField()),
                ('bottom_hash', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(max_length=2048)),
                ('slat', models.CharField(max_length=500)),
                ('sign', models.CharField(max_length=2048)),
            ],
        ),
    ]
