# Generated by Django 4.2.6 on 2023-11-02 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Miner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votes',
            old_name='slat',
            new_name='salt',
        ),
    ]
