# Generated by Django 3.2.20 on 2023-11-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miner', '0002_rename_slat_votes_salt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='slat',
            new_name='salt',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='id',
        ),
        migrations.AddField(
            model_name='block',
            name='nonce',
            field=models.CharField(default=100, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='time_stamp',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='votes',
            name='vote',
            field=models.CharField(max_length=2048, primary_key=True, serialize=False),
        ),
    ]
