# Generated by Django 3.2.20 on 2023-11-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miner', '0003_auto_20231107_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='counter',
            field=models.BigIntegerField(auto_created=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='bottom_hash',
            field=models.CharField(max_length=1024, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='block',
            name='vote',
            field=models.CharField(max_length=2048, unique=True),
        ),
    ]
