# Generated by Django 3.2.20 on 2023-11-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miner', '0004_auto_20231108_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='counter',
            field=models.BigIntegerField(auto_created=True, default=1, editable=False),
        ),
    ]
