# Generated by Django 3.2.20 on 2023-11-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miner', '0005_alter_block_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='sign',
            field=models.CharField(default='null', max_length=2048),
            preserve_default=False,
        ),
    ]
